; Please make sure Everything is not running before modifying this file.

[etp_server64.dll]
enabled=0
welcome_message=
port=21
username=
password=
log_file_name=
logging_enabled=1
log_max_size=4194304
log_delta_size=524288
allow_file_download=1
bindings=
allow_ftp_port=1
check_ftp_data_connection_ip=1
allow_disk_access=0

[everything_server64.dll]
enabled=0
port=14630
bindings=
index_snapshot_cache_timeout=60000
index_snapshot_max_count=8
users=""
password=
include_only_path=
include_only_mount=
organization=
key=

[http_server64.dll]
enabled=1
title_format=
port=50000
username=
password=
home=
default_page=
log_file_name=
logging_enabled=1
log_max_size=4194304
log_delta_size=524288
allow_file_download=1
bindings=
items_per_page=32
show_drive_label=0
strings_filename=
header=
allow_query_access=0
allow_disk_access=0
allow_full_access=0
default_sort=3
default_sort_ascending=0
